"""IRISMessage entity for representing IRIS messages.log entries."""

import re
from datetime import datetime

from pydantic import Field, field_validator

from src.models.base import BaseModel

# IRIS timestamp format: MM/DD/YY-HH:MM:SS:mmm
IRIS_TIMESTAMP_PATTERN = re.compile(r"^\d{2}/\d{2}/\d{2}-\d{2}:\d{2}:\d{2}:\d{3}$")

# IRIS category format: Dot-separated words (e.g., Generic.Event, Database.MountedRW)
IRIS_CATEGORY_PATTERN = re.compile(r"^[A-Za-z]+(\.[A-Za-z]+)*$")


class IRISMessage(BaseModel):
    """Represents a single entry from InterSystems IRIS messages.log file.

    Format matches: MM/DD/YY-HH:MM:SS:mmm (PID) SEVERITY [CATEGORY] Message text

    Example:
        11/14/25-09:45:57:762 (50803) 2 [Generic.Event] Kerberos authentication unavailable
    """

    timestamp: str = Field(
        ...,
        description="IRIS format timestamp MM/DD/YY-HH:MM:SS:mmm",
        examples=["11/14/25-09:45:55:657"],
    )

    process_id: int = Field(
        ...,
        description="Unix process ID of IRIS daemon",
        ge=1,
        le=999999,
        examples=[50745, 50803],
    )

    severity: int = Field(
        ...,
        description="Error severity level: 0=Info, 1=Warning, 2=Error, 3=Severe",
        ge=0,
        le=3,
    )

    category: str = Field(
        ...,
        description="IRIS message category (dot-separated hierarchy)",
        examples=["Generic.Event", "Database.MountedRW", "WriteDaemon.Started"],
    )

    message_text: str = Field(
        ...,
        description="Human-readable message content",
        min_length=1,
        max_length=500,
    )

    generated_at: datetime = Field(
        default_factory=lambda: datetime.now(datetime.now().astimezone().tzinfo),
        description="ISO 8601 timestamp when message was generated by Instance",
    )

    @field_validator("timestamp")
    @classmethod
    def validate_timestamp(cls, v: str) -> str:
        """Validate IRIS timestamp format."""
        if not IRIS_TIMESTAMP_PATTERN.match(v):
            raise ValueError(
                f"Invalid IRIS timestamp format. Expected MM/DD/YY-HH:MM:SS:mmm, got: {v}"
            )
        return v

    @field_validator("category")
    @classmethod
    def validate_category(cls, v: str) -> str:
        """Validate IRIS category format."""
        if not IRIS_CATEGORY_PATTERN.match(v):
            raise ValueError(
                f"Invalid IRIS category format. Expected dot-separated words, got: {v}"
            )
        return v

    def to_log_format(self) -> str:
        """Convert to IRIS messages.log format string.

        Returns:
            IRIS log entry: timestamp (PID) severity [category] message
        """
        return (
            f"{self.timestamp} ({self.process_id}) {self.severity} "
            f"[{self.category}] {self.message_text}"
        )
